-- Task 3

-- 14. Find the total number of couriers handled by each employee
SELECT EmployeeID , COUNT(OrderID) as 'Couriers Handled'
FROM Orders
GROUP BY EmployeeID;

-- 15. Calculate the total revenue generated by each location
SELECT Location.LocationID , LocationName ,SUM(Amount) as 'Revenue Generated'
FROM Payment
RIGHT JOIN location 
ON Payment.LocationID = Location.LocationID
GROUP BY LocationID, LocationName;

-- 16. Find the total number of couriers delivered to each location
SELECT l.LocationID , COUNT(OrderID) as Couriers_Delivered
FROM Payment p
RIGHT OUTER JOIN Location l
ON p.locationID = l.locationID
GROUP BY LocationID;

-- 17. Find the courier with the highest average delivery time
SELECT CourierID, AVG(DATEDIFF(deliverydate,paymentdate)) as Avg_delivery_time
FROM Payment
JOIN Orders
ON Payment.OrderID = Orders.OrderID
GROUP BY CourierID
ORDER BY Avg_delivery_time DESC
LIMIT 1;

-- 18. Find Locations with Total Payments Less Than a Certain Amount
SELECT Location.LocationID , LocationName ,SUM(Amount) as 'Revenue Generated'
FROM Payment
RIGHT OUTER JOIN Location 
ON Payment.LocationID = Location.LocationID
GROUP BY LocationID , LocationName
HAVING SUM(Amount) < 500;

-- 19. Calculate Total Payments per Location
SELECT LocationID , COUNT(PaymentID)
FROM Payment
GROUP BY LocationID;

-- 20. Retrieve couriers who have received payments totaling more than $1000 in a specific location(LocationID = X):
SELECT CourierID ,Payment.LocationID, SUM(Amount) as 'Revenue_Generated'
FROM Payment
JOIN Location 
ON Payment.LocationID = Location.LocationID
WHERE Payment.LocationID = '600045'
GROUP BY CourierID , LocationID
HAVING Revenue_Generated > 1000;

-- 21. Retrieve couriers who have received payments totaling more than $1000 after a certain date (PaymentDate > 'YYYY-MM-DD')
SELECT Payment.CourierID , Name , SUM(Amount) as 'Revenue_Generated'
FROM Payment
JOIN CourierCompany
ON CourierCompany.CourierID = Payment.CourierID
WHERE PaymentDate >= '2024-01-01'
GROUP BY CourierID , Name
HAVING Revenue_Generated > 1000;

-- 22. Retrieve locations where the total amount received is more than $5000 before a certain date (PaymentDate > 'YYYY-MM-DD')
SELECT LocationID , SUM(Amount) as 'Revenue_Generated'
FROM Payment 
WHERE PaymentDate <= '2024-01-12'
GROUP BY LocationID
HAVING Revenue_Generated > 5000; -- verified with total amount greater than 500 before a certain date

